name: Assign to Project

on:
  issues:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to Master Board
    steps:
      - name: Assign NEW issues to master board
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: github.event.action == 'opened'
        with:
          project: 'https://github.com/rizqitsani/mppl-frontend/projects/1'
